version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 6
    labels: [ "dependencies", "automated" ]
    commit-message: { prefix: "deps", include: "scope" }

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: [ "ci", "automated" ]
